---
- name: Check for existing Zscaler Agent installation.
  stat:
    path: /Applications/Zscaler.app
  register: zscaler_installed

- name: Download DMG package to local tmp.
  get_url:
    url: "{{ zscaler_mac_app }}"
    dest: "{{ zscaler_mac_dest }}"
    force: no
    mode: 644
  become: no
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install Zscaler Agent on the machine
  shell: "{{ zscaler_mac_dest }}"/zscaler.app/MacOS/installbuilder.sh --mode unattended --unattendedmodeui none
  args:
    warn: no
  when: zscaler_installed.stat.exists == False
