---
- name: Check for existing Zscaler Agent installation.
  win_stat:
    path: "C:\\Program Files (x86)\\Zscaler"
  register: zscaler_installed

- name: Download MSI to local directory.
  win_get_url:
    url: "{{ zscaler_windows_msi }}"
    dest: "{{ zscaler_windows_dest }}"
    force: no
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install Zscaler Agent on the Windows
  win_package:
    path: "{{ zscaler_windows_dest }}"
    productid: auto
    state: present
    arguments:
    - CLOUDNAME="{{install_win_CLOUDNAME}}"
    - DEVICETOKEN="{{install_win_DEVICETOKEN}}"
    - HIDEAPPUIONLUNCH="{{install_win_HIDEAPPUIONLUNCH}}"
    - POLICYTOKEN="{{install_win_POLICYTOKEN}}"
    - REINSTALLDRIER="{{install_win_REINSTALLDRIER}}"
    - STRICTENFORCMENT="{{install_win_STRICTENFORCMENT}}"
    - USERDOMAIN="{{install_win_USERDOMAIN}}"
    ignore_errors: "{{ ansible_check_mode }}"
